server:
  host: "127.0.0.1"
  port: 8888
  db-type: "mysql"
  prefix: "/gra"
  model: "debug"
  open-sso: true
casdoor-config:
  endpoint: "http://123.207.197.234:8000"
  client-id: "813246115a8218f642ec"
  client-secret: "8b4cff100950e4104d6f85543bea5fdd569ff34a"
  organization-name: "vm_group"
  application-name: "vm_manager"
mysql:
  username: "gin-react_admin"
  password: "Tr4i7yNccYnXC2HC"
  host: "123.207.197.234"
  port: "3306"
  db-name: "gin-react_admin"
  engine: "innoDB"
file-server:
  type: "local"

local-file-server:
  file-path: ""
  